### ISSUE TITLE
Http request are slower as compared to TCP

### ISSUE THREAD

**Issue by writeaditya** [gphat/wabisabi#57]
Hi,

I need to understand why my http request using this client is slow. I'm not able to figure out. I'm using this client in my spark application to connect and query elastic search but however, it is performing slower even then Cassandra. Like for 50K unique partition key, amount of time taken by wabisabi is almost 3 times than it was fetching through direct read request from Cassandra. It is simple request to fetch the entire data of each partition in a loop. 

Also, since this client is asynchronous , therefore i have to use wait inside executors for the response to be successful, otherwise it always comes not of executors in spark without fetching data. 

Thanks, any suggestions for my problems.

**Comment by gphat** [comment]
There are two questions here. I'm going to skip past the "why is this slower than Cassandra" since that's a question about ElasticSearch and not this library. I am assuming you're instead interested in why this client is slower versus some other client.

This library uses dispatch under the hood. I am not aware at the moment of any way to inspect it further, but I'm happy to accept patches or suggestions that would either make that easier to discern or that would correct any misuse of dispatch.

Either way, without more information this question sounds more like an ES problem than one about this library.
